//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderShare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        public string AccountNo { get; set; }
        public string Name { get; set; }
        public string Broker { get; set; }
        public Nullable<decimal> Equity { get; set; }
        public Nullable<decimal> FreeMargin { get; set; }
        public string Currency { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public long ID { get; set; }
    }
}
